language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "pip install flake8"
    - "pip install ."
script:
    - "dotlink --debug --help"
    - "flake8 --show-source dotlink"
notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.org#noswap"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
        use_notice: true
        skip_join: true
